"""
backtest/engine.py
------------------
Simulates trading day-by-day using the signals generated by the strategy.

The engine tracks two things at all times:
  - cash       : dollars not currently invested
  - shares_held: number of stock shares currently owned

On a BUY signal  → spend all available cash to buy as many shares as possible
On a SELL signal → sell all shares and convert back to cash
On HOLD days     → do nothing

Portfolio value each day = cash + (shares_held × today's closing price)

We also simulate a "buy-and-hold" benchmark: what if you just bought on
day 1 and never sold? Comparing our strategy to this baseline is how we
judge whether the strategy actually adds value.
"""

import pandas as pd


def run_backtest(df: pd.DataFrame, initial_capital: float = 10_000.0) -> pd.DataFrame:
    """
    Simulate the SMA crossover strategy on the price+signal DataFrame.

    Parameters
    ----------
    df              : DataFrame output from compute_signals() — must have
                      columns 'Close' and 'Signal'.
    initial_capital : Starting cash in dollars (default $10,000).

    Returns
    -------
    The DataFrame with these new columns added:
        'Cash'            : cash held on that day (not invested)
        'Shares'          : number of shares held on that day
        'Portfolio_Value' : total value = cash + shares × price
        'BuyHold_Value'   : value if we had just bought and held since day 1
        'Trade'           : human-readable label ('BUY', 'SELL', or '')
    """

    df = df.copy()

    # --- State variables ---
    # These track the current state of our simulated portfolio.
    cash = initial_capital
    shares_held = 0.0

    # Pre-allocate lists to store each day's state.
    # (Appending to a list and converting once is much faster than updating
    # a DataFrame row-by-row inside a loop.)
    cash_history = []
    shares_history = []
    trade_labels = []

    # --- Simulate day by day ---
    for date, row in df.iterrows():
        price = row["Close"]
        signal = row["Signal"]
        label = ""

        if signal == 1:
            # BUY: use all available cash to purchase shares.
            # Integer division (//) ensures we buy whole shares only.
            shares_to_buy = cash // price
            shares_held += shares_to_buy
            cash -= shares_to_buy * price
            if shares_to_buy > 0:
                label = "BUY"

        elif signal == -1:
            # SELL: liquidate the entire position back to cash.
            cash += shares_held * price
            shares_held = 0.0
            label = "SELL"

        cash_history.append(cash)
        shares_history.append(shares_held)
        trade_labels.append(label)

    df["Cash"] = cash_history
    df["Shares"] = shares_history
    df["Trade"] = trade_labels

    # Portfolio value on any given day is cash plus the market value of shares.
    df["Portfolio_Value"] = df["Cash"] + df["Shares"] * df["Close"]

    # Buy-and-hold benchmark: how many shares could we have bought on day 1?
    first_price = df["Close"].iloc[0]
    shares_if_held = initial_capital // first_price
    leftover_cash = initial_capital - shares_if_held * first_price
    df["BuyHold_Value"] = shares_if_held * df["Close"] + leftover_cash

    return df
